import nextConfig from 'eslint-config-next';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

const config = [
  ...nextConfig,
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'build/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      '.pb/**',
      'data/**',
      // Generated by @serwist/next at build time from app/sw.ts. The
      // bundle is minified worker code that should never be linted as
      // if it were source — it re-emits on every build and any churn
      // in its minified output is noise (pre-existing this-alias
      // error discovered during the Phase 9 UX audit).
      'public/sw.js',
    ],
  },
  {
    // Test files routinely need `any` casts for global mocks (fetch, window, globalThis).
    // Relax the strictest typing rules for tests only — production code remains strict.
    files: ['tests/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    // PocketBase migrations + JSVM hook files run INSIDE PB's embedded goja
    // runtime, not Node/Next. They must use the `/// <reference path="...">`
    // directive (PB's documented pattern — the referenced types.d.ts is
    // auto-generated by PB into pb_data/ and provides editor hints for
    // globals like `migrate`, `onBootstrap`, `$app`, `Collection`, etc.).
    // ESM `import` does not work in goja. These files also use catch(_)
    // stubs for idempotent down-migrations.
    files: ['pocketbase/pb_migrations/**/*.js', 'pocketbase/pb_hooks/**/*.js'],
    rules: {
      '@typescript-eslint/triple-slash-reference': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { caughtErrors: 'none' }],
    },
  },
];

export default config;
